<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6sijOjL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6sijOjL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6sijOjL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6sijOjL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6sijOjL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6sijOjL',
    'container.build_id' => '805102d2',
    'container.build_time' => 1620586219,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6sijOjL');
